"""
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""


def fibonacci_sum(n: int) -> int:
    """
    Calculate the sum of even-valued Fibonacci numbers up to n.

    Args:
        n: The upper limit for Fibonacci numbers to consider

    Returns:
        The sum of all even Fibonacci numbers not exceeding n
    """
    a = 0
    b = 1
    c = 0
    total = 0

    while c < n:
        c = a + b
        if c % 2 == 0:
            total += c
        a = b
        b = c

    return total


def main() -> None:
    """Execute the main program logic."""
    print(fibonacci_sum(4 * pow(10, 6)))


if __name__ == "__main__":
    main()